---
title: "poblacio general"
author: "ETN"
date: "`r Sys.time()`"
output:
  html_document:
    toc: yes
    toc_float: yes
    css: styles.css
  pdf_document:
    toc: yes
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r}
library(tidyverse)
library(data.table)
library(readxl)

taula = read_excel('~/idiap/data/ododnt_girona/Escoles_Giona_3_mod.xlsx')
```

```{r}
summary_table <- taula %>%
  group_by(Grup) %>%
  summarise(
    total_sum = sum(total, na.rm = TRUE),
    lliures_car_sum = sum(lliures_car, na.rm = TRUE),
    med_caod_mean = mean(med_caod, na.rm = TRUE),
    med_co_mean = mean(med_co, na.rm = TRUE),
    perc_sans_mean = mean(`%sans`, na.rm = TRUE)
  )

summary_table_coles <- taula %>%
  group_by(escola, Grup) %>%
  summarise(
    total_sum = sum(total, na.rm = TRUE),
    lliures_car_sum = sum(lliures_car, na.rm = TRUE),
    med_caod_mean = mean(med_caod, na.rm = TRUE),
    med_co_mean = mean(med_co, na.rm = TRUE),
    perc_sans_mean = mean(`%sans`, na.rm = TRUE)
  )
```

# Results {.tabset}

## Població total

```{r}
print('Test de normalitat')
shapiro.test(summary_table_coles$total_sum)$p.value
print('t.test')
t.test(total_sum ~ Grup, data = summary_table_coles)$p.value
```

```{r}

boxplot(summary_table_coles$total_sum ~ summary_table_coles$Grup,
        main = paste("Boxplot of total population by Group"),
        xlab = "Group",
        ylab = 'Total població')

```

## Lliures caries

```{r}
print('Test de normalitat')
shapiro.test(summary_table_coles$lliures_car_sum)$p.value
print('t.test')
t.test(lliures_car_sum ~ Grup, data = summary_table_coles)$p.value
```

```{r}

boxplot(summary_table_coles$lliures_car_sum ~ summary_table_coles$Grup,
        main = paste("Boxplot of caries by Group"),
        xlab = "Group",
        ylab = 'Lliures caries')

```

## CAOD

```{r}
print('Test de normalitat')
shapiro.test(summary_table_coles$med_caod_mean)$p.value
print('wilcox test')
wilcox.test(med_caod_mean ~ Grup, data = summary_table_coles)$p.value
```

```{r}

boxplot(summary_table_coles$med_caod_mean ~ summary_table_coles$Grup,
        main = paste("Boxplot of CAOD by Group"),
        xlab = "Group",
        ylab = 'CAOD')

```

## CO

```{r}
print('Test de normalitat')
shapiro.test(summary_table_coles$med_co_mean)$p.value
print('wilcox test')
wilcox.test(med_co_mean ~ Grup, data = summary_table_coles)$p.value
```

```{r}

boxplot(summary_table_coles$med_co_mean ~ summary_table_coles$Grup,
        main = paste("Boxplot of CO by Group"),
        xlab = "Group",
        ylab = 'CO')

```

## Percentatge sans

```{r}

print('Test de normalitat')
shapiro.test(taula$`%sans`)$p.value
print('fisher test')

setDT(taula)
group_a_surpassed <- sum(taula[Grup=='A']$lliures_car)
group_a_total <- sum(taula[Grup=='A']$total)
group_b_surpassed <- sum(taula[Grup=='B']$lliures_car)
group_b_total <- sum(taula[Grup=='B']$total)

group_a_not_surpassed <- group_a_total - group_a_surpassed
group_b_not_surpassed <- group_b_total - group_b_surpassed

contingency_table <- matrix(c(group_a_surpassed, group_a_not_surpassed,
                              group_b_surpassed, group_b_not_surpassed),
                            nrow = 2, byrow = TRUE)
fisher.test(contingency_table)$p.value
```

```{r}

boxplot(summary_table_coles$perc_sans_mean ~ summary_table_coles$Grup,
        main = paste("Boxplot of healthy percentage by Group"),
        xlab = "Group",
        ylab = "percentatge sans")

```